import type { CityDefinition } from "@/types/content";
import { troyMi } from "./troy-mi";

/**
 * City landing pages, nested under their county.
 *
 * GENERATED by tools/build-city-index.mjs — do not edit by hand. Add a city by
 * creating src/content/cities/<slug>.ts exporting a camelCase const named after
 * the slug, then re-run the script.
 */
export const cities: CityDefinition[] = [
  troyMi,
];

export function getCityBySlug(slug: string): CityDefinition | undefined {
  return cities.find((c) => c.slug === slug);
}

export function getCitiesByCounty(countySlug: string): CityDefinition[] {
  return cities
    .filter((c) => c.countySlug === countySlug)
    .sort((a, b) => a.cityName.localeCompare(b.cityName));
}
